version: "3.3"

services:
  postgres:
    container_name: django_app_postgres
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  redis:
    container_name: django_app_redis
    image: redis:7-alpine
    ports:
      - 6379:6379

volumes:
  postgres_data: